name: Push To Dev Repo

on:
  push:
    branches:
      - dev # dev 브랜치에 푸시될 때 트리거

jobs:
  sync-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout original repository
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Configure Git
        run: |
          git config --global user.name "SoJuSo"
          git config --global user.email "asdfg7123@gmail.com"

      - name: Add forked repository as remote
        run: |
          git remote add fork https://github.com/SoJuSo/grouphi-mvp-fe.git
          git fetch fork dev

      - name: Force reset forked dev branch to upstream dev
        run: |
          git reset --hard fork/dev
          git push --force fork dev
        env:
          GITHUB_TOKEN: ${{ secrets.DEV_ACCESS_TOKEN }}
